{{- if .Values.profiseeRunTime.isPaaS }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  Profisee.server: |
    {{.Values.profiseeRunTime.externalDnsName}}:53 {
        rewrite name {{.Values.profiseeRunTime.externalDnsName}}:53 nginx-ingress-nginx-controller.profisee.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ipv6.arpa
            ttl 30
        }
    }
{{- end }}
