sqlServer:
    name: "{sql_server_name}.privatelink.database.windows.net" #this is the sql server for the regio/env
    databaseName: "{customer_database_name}"
    userName: "" #this will be the mi client_id
    password: "" #this will be null when we switch to use the MI, set to the current admin pw for the sql_server
profiseeRunTime:
    useLetsEncrypt: false
    adminAccount: "{customer_email}"
    fileRepository:
        accountName: "{customer_storage_account_name}"
        userName: "Azure\\{customer_storage_account_name}"
        password: "{customer_storage_account_key}"
        logonType: "NewCredentials"
        location: "\\\\{customer_storage_account_name}.file.core.windows.net\\files"
        fileShareName: "files"
    externalDnsUrl: "https://profiseecloud.com" #Leave for now but will either tst.profiseecloud.com or stg.profiseecloud.com or profiseecloud.com
    externalDnsName: "profiseecloud.com" #Leave for now but will either tst.profiseecloud.com or stg.profiseecloud.com or profiseecloud.com
    webAppName: "{customer_name}" #this is what ends up here in the url https://tst.profiseecloud.com/customername
    deployIngressRule: true
    isPaaS: false
    oidc:
        name: "Azure Active Directory" #Leave for now but will be supplied per customer in near future
        authority:  #Leave for now but will be supplied per customer in near future
        clientId:  #Leave for now but will be supplied per customer in near future
        clientSecret: "" #Leave for now but will be supplied per customer in near future
        usernameClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" #Leave for now but will be supplied per customer in near future
        userIdClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier" #Leave for now but will be supplied per customer in near future
        firstNameClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" #Leave for now but will be supplied per customer in near future
        lastNameClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" #Leave for now but will be supplied per customer in near future
        emailClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" #Leave for now but will be supplied per customer in near future
    clusterNodeCount: 1
clusterNode:
    limits:
      cpu: 4 #Leave for now but will be supplied per customer in near future
      memory: 16G #Leave for now but will be supplied per customer in near future
    requests:
      cpu: 1 #Leave for now but will be supplied per customer in near future
      memory: 1000M #Leave for now but will be supplied per customer in near future
image:
    registry: "profisee.azurecr.io"
    repository: "profiseeplatform"
    tag: "2021r3.0.saas"
    auth: | #Leave for now but will be supplied per customer in near future
licenseFileData:
preInitScriptData: Cg==
postInitScriptData:
oidcFileData: |
    $OIDC
tlsCert: |
    NA
tlsKey: |
    NA
cloud:
    azure:
      isProvider: true
      useKeyVault: false
      keyVault: #NA
        identity:
          clientId: ""
          resourceId: ""
        secrets:
          sqlUserName: ""
          sqlPassword: ""
          tlsCertificate: ""
          license: ""
        name: ""
        resourceGroup: ""
        subscriptionId: ""
        tenantId: ""
        clusterClientId: ""
      useManagedIdentity: false
      managedIdentity:
        name: ""
        clientId: ""
        resourceId: ""
      purview:
        clientId: "" #Blank for now but will be supplied in near future
        clientSecret: "" #Blank for now but will be supplied in near future
        tenantId: "" #Blank for now but will be supplied in near future
        url: ""  #Blank for now but will be supplied in near future
        collectionId: "" #Blank for now but will be supplied in near future
    aws:
      isProvider: false
    google:
      isProvider: false